### ISSUE TITLE
Detect addition/removal of const

### ISSUE THREAD

**Issue by untitaker** [getsentry/json-schema-diff#15]
Addition of const is a breaking change, removal is not one.

**Comment by 6293** [comment]
this looked easy at a first glance but this comes up to my mind:

```json
{
  "lhs": { "const": { "key": "value" } },
  "rhs": { "properties": { "key": { "const": "value" } } }
}
```

nice if we manage to produce no diff on this

**Comment by untitaker** [comment]
i think it should be easiest to normalize lhs into rhs before comparing
