### ISSUE TITLE
Better support for anyOf

### ISSUE THREAD

**Issue by untitaker** [getsentry/json-schema-diff#16]
Any nontrivial construction of anyOf can confuse json-schema-diff in printing erronenous diffs. For example, those two schemas are identical, but produce diffs:

```
{"anyOf": [{"type": "string"}, {"type": "integer"}]}
```

```
{"type": ["string", "integer"]}
```

**Comment by untitaker** [comment]
thank you for working on this @6293. May I ask if you have a usecase for json-schema-diff or are just implementing those features for fun?

**Comment by 6293** [comment]
Just for fun. If you don't mind I will keep adding support for other json schema keywords
